### ISSUE TITLE
testFengzhuang.py中post/get

### ISSUE THREAD

**Issue by longlong1013** [liwanlei/jiekou-python3#1]
testFengzhuang.py下，方式写了GET，请求用了POST，请确认？

23	elif self.fangshi=="GET":
24		self.parem = {'key': self.key, 'info': self.connent}
25		response = reques.post(self.url, self.parem)

**Comment by liwanlei** [comment]
恩好，我去看下，我本地没问题，可能推送时候出现的问题，我检查下，谢谢提醒。




发自网易邮箱大师
在2017年08月09日 17:02，longlong1013 写道：

testFengzhuang.py下，方式写了GET，请求用了POST，请确认？

23 elif self.fangshi=="GET":
24 self.parem = {'key': self.key, 'info': self.connent}
25 response = reques.post(self.url, self.parem)

**Comment by longlong1013** [comment]
不好意思，再打扰下哦
直接把post改为get还是有问题的。因为你重新封装了reques,其中get只传了url。
