### ISSUE TITLE
头部信息存在哪里

### ISSUE THREAD

**Issue by chendafei** [liwanlei/jiekou-python3#14]
你好，请问头部信息存储在测试用例的哪里呀

**Comment by liwanlei** [comment]
你是说请求头吗

**Comment by chendafei** [comment]
您好，请问你github上面的接口自动化测试框架不更新了吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liwanlei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 下午4:24
收件人:&nbsp;"liwanlei/jiekou-python3"<jiekou-python3@noreply.github.com&gt;;
抄送:&nbsp;"Nice"<1657214485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liwanlei/jiekou-python3] 头部信息存在哪里 (#14)



哪个头部信息
 
 
 
 
 | |
 李雷雷
 |
 |
 邮箱：leileili126@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2019年10月21日 16:21，chenfei 写道：
 
 你好，请问头部信息存储在测试用例的哪里呀

**Comment by liwanlei** [comment]
目前暂时没有更新计划。




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2020年04月03日 15:43，chenfei 写道：

您好，请问你github上面的接口自动化测试框架不更新了吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liwanlei"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 下午4:24
收件人:&nbsp;"liwanlei/jiekou-python3"<jiekou-python3@noreply.github.com&gt;;
抄送:&nbsp;"Nice"<1657214485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liwanlei/jiekou-python3] 头部信息存在哪里 (#14)



哪个头部信息




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2019年10月21日 16:21，chenfei 写道：

你好，请问头部信息存储在测试用例的哪里呀

**Comment by chendafei** [comment]
请问方便加下你的联系方式吗 谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liwanlei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 下午3:55
收件人:&nbsp;"liwanlei/jiekou-python3"<jiekou-python3@noreply.github.com&gt;;
抄送:&nbsp;"Nice"<1657214485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liwanlei/jiekou-python3] 头部信息存在哪里 (#14)





 目前暂时没有更新计划。
 
 
 
 
 | |
 李雷雷
 |
 |
 邮箱：leileili126@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月03日 15:43，chenfei 写道：
 
 您好，请问你github上面的接口自动化测试框架不更新了吗？
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"liwanlei"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2019年10月21日(星期一) 下午4:24
 收件人:&amp;nbsp;"liwanlei/jiekou-python3"<jiekou-python3@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"Nice"<1657214485@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [liwanlei/jiekou-python3] 头部信息存在哪里 (#14)
 
 
 
 哪个头部信息
 
 
 
 
 | |
 李雷雷
 |
 |
 邮箱：leileili126@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2019年10月21日 16:21，chenfei 写道：
 
 你好，请问头部信息存储在测试用例的哪里呀

**Comment by liwanlei** [comment]
微信lwl930423




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2020年04月03日 15:57，chenfei 写道：

请问方便加下你的联系方式吗 谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liwanlei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 下午3:55
收件人:&nbsp;"liwanlei/jiekou-python3"<jiekou-python3@noreply.github.com&gt;;
抄送:&nbsp;"Nice"<1657214485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liwanlei/jiekou-python3] 头部信息存在哪里 (#14)





目前暂时没有更新计划。




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2020年04月03日 15:43，chenfei 写道：

您好，请问你github上面的接口自动化测试框架不更新了吗？




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:&amp;nbsp;"liwanlei"<notifications@github.com&amp;gt;;
发送时间:&amp;nbsp;2019年10月21日(星期一) 下午4:24
收件人:&amp;nbsp;"liwanlei/jiekou-python3"<jiekou-python3@noreply.github.com&amp;gt;;
抄送:&amp;nbsp;"Nice"<1657214485@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
主题:&amp;nbsp;Re: [liwanlei/jiekou-python3] 头部信息存在哪里 (#14)



哪个头部信息




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2019年10月21日 16:21，chenfei 写道：

你好，请问头部信息存储在测试用例的哪里呀

**Comment by chendafei** [comment]
好的 谢谢🙏


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liwanlei"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 下午3:58
收件人:&nbsp;"liwanlei/jiekou-python3"<jiekou-python3@noreply.github.com&gt;;
抄送:&nbsp;"Nice"<1657214485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liwanlei/jiekou-python3] 头部信息存在哪里 (#14)





 微信lwl930423
 
 
 
 
 | |
 李雷雷
 |
 |
 邮箱：leileili126@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月03日 15:57，chenfei 写道：
 
 请问方便加下你的联系方式吗 谢谢！
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"liwanlei"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年4月3日(星期五) 下午3:55
 收件人:&amp;nbsp;"liwanlei/jiekou-python3"<jiekou-python3@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"Nice"<1657214485@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;Re: [liwanlei/jiekou-python3] 头部信息存在哪里 (#14)
 
 
 
 
 
 目前暂时没有更新计划。
 
 
 
 
 | |
 李雷雷
 |
 |
 邮箱：leileili126@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年04月03日 15:43，chenfei 写道：
 
 您好，请问你github上面的接口自动化测试框架不更新了吗？
 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------
 发件人:&amp;amp;nbsp;"liwanlei"<notifications@github.com&amp;amp;gt;;
 发送时间:&amp;amp;nbsp;2019年10月21日(星期一) 下午4:24
 收件人:&amp;amp;nbsp;"liwanlei/jiekou-python3"<jiekou-python3@noreply.github.com&amp;amp;gt;;
 抄送:&amp;amp;nbsp;"Nice"<1657214485@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;
 主题:&amp;amp;nbsp;Re: [liwanlei/jiekou-python3] 头部信息存在哪里 (#14)
 
 
 
 哪个头部信息
 
 
 
 
 | |
 李雷雷
 |
 |
 邮箱：leileili126@163.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2019年10月21日 16:21，chenfei 写道：
 
 你好，请问头部信息存储在测试用例的哪里呀
