### ISSUE TITLE
请问支持纯的dubbo服务吗

### ISSUE THREAD

**Issue by fengbenming** [liwanlei/jiekou-python3#6]
基于telnet的invoke不支持 List<Integer>类型的参数，很头疼

**Comment by liwanlei** [comment]
这个目前没有特别往dubbo方面发展，现在主要点放在了http协议

**Comment by liwanlei** [comment]
不支持




| |
李雷雷
|
|
邮箱：leileili126@163.com
|

签名由 网易邮箱大师 定制

在2019年07月25日 15:22，fengbenming 写道：

Closed #6.
