### ISSUE TITLE
怎么启动

### ISSUE THREAD

**Issue by HelenJane** [liwanlei/jiekou-python3#8]
请问下，服务怎么启动呢？

**Comment by liwanlei** [comment]
这个没有服务把




| |
leileili126
|
|
邮箱：leileili126@163.com
|

Signature is customized by Netease Mail Master

在2018年11月21日 15:22，Helen 写道：

请问下，服务怎么启动呢？

**Comment by HelenJane** [comment]
哦哦，知道了，原以为是平台~
