### ISSUE TITLE
testCase下的case.py文件

### ISSUE THREAD

**Issue by lykion** [liwanlei/jiekou-python3#9]
在下面截取的代码部分中，应该将断言通过出的‘continue’改成‘break’，不然的话，断言通过，case会一直不停的执行
for i in range(len(listurl)):
        while error_num<=Config_Try_Num+1:
            api = TestApi(url=TestPlanUrl+listurl[i], key=listkey[i], connent=listconeent[i], fangshi=listfangshi[i])
            apijson = api.getJson()
            if apijson['code'] == 0:
                LOG.info('inputdata> 参数:%s, url:%s ,返回:%s,预期:%s' % (listconeent[i], listurl[i], apijson, listqiwang[i]))
                assert_re = assert_in(asserqiwang=listqiwang[i], fanhuijson=apijson)
                if assert_re['code'] == 0:
                    list_json.append(apijson['result'])
                    listrelust.append('pass')
                    list_pass += 1
                    error_num=0
                    continue

**Comment by liwanlei** [comment]
这个地方的代码应该已经优化了
